# Mutation operator

GA order of operation:
1. Calculate the fitness of each chromosome in the current generation.
2. Select the parents from the current generation that will be used to make the next generation.
3. Perform crossover of the parents to make children that will be the chromosomes in the next generation.
4. **Mutate the children made in step 3.**

Now that we have performed crossover, the final step to get a new generation of the population is to mutate the children from the current generation.

# Probability of mutation
Each individual gene in the genome will be mutated based on the mutation probability. Here, we set it to 30% so you can easily observe the mutation of the genome. However, when running the GA, you will want to systematically explore different mutation rates to find the one that is right for the problem you are trying to solve (30% will almost certainly be too high).

In [1]:
import numpy as np

PROB_MUTATION = 0.3

child_1 = np.array([1,1,1,1,1,1,1,1,1,1,
                    0,0,0,0,0,0,0,0,0,0])

print(f"child_1: {child_1}")

child_1: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]


## Mutation probability

We now loop through the index of each gene in the genome and if rand_num is less than the mutation probability, PROB_MUTATION, then we mutate the gene at index i. In the case of a binary list, this means flipping the bit.

In [3]:
mutated_child_1 = child_1.copy()

for i in range(len(child_1)):
    
    rand_num = np.random.rand()
    
    if rand_num < PROB_MUTATION:
        print()
        print(f"{round(rand_num, 5)} < {PROB_MUTATION} so mutating gene {i}")
        
        if mutated_child_1[i] == 0:
            mutated_child_1[i] = 1
        else:
            mutated_child_1[i] = 0
        
        print(f"new child_1: {mutated_child_1} (original: {child_1})")
        print()
    else:
        print(f"Skipping gene {i}")
        

Skipping gene 0
Skipping gene 1

0.16686 < 0.3 so mutating gene 2
new child_1: [1 1 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0] (original: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0])


0.04469 < 0.3 so mutating gene 3
new child_1: [1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0] (original: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0])

Skipping gene 4
Skipping gene 5
Skipping gene 6

0.13291 < 0.3 so mutating gene 7
new child_1: [1 1 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0] (original: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0])

Skipping gene 8
Skipping gene 9
Skipping gene 10
Skipping gene 11

0.12953 < 0.3 so mutating gene 12
new child_1: [1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0] (original: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0])

Skipping gene 13

0.08508 < 0.3 so mutating gene 14
new child_1: [1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 0 0 0 0 0] (original: [1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0])


0.15817 < 0.3 so mutating gene 15
new child_1: [1 1 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0] (original: [1 1 1 1 1 1 1

## Mutation of the entire population
What we actually want to do is mutate every gene in every genome for all chromosomes in the population.

In [4]:
import random

PROB_MUTATION = 0.3
POPULATION_SIZE = 20

# make a population of chromosomes
chromosome = np.array([0,0,1,0,1,0,1,1,1,1,1,1,0,1,1,1,0,0,1,0])
population = np.empty((0,len(chromosome)))
for i in range(POPULATION_SIZE):
    random.shuffle(chromosome)
    population = np.vstack((population, chromosome))
    
print("Original population")
print(population)
print()

mutated_population = population.copy()

# mutate the population
for i in range(len(population)): # for each chromosome
    for j in range(len(population[i])): # for each gene in the chromosome

        if np.random.rand() < PROB_MUTATION:

            if mutated_population[i][j] == 0:
                mutated_population[i][j] = 1
            else:
                mutated_population[i][j] = 0

print("Mutated population")
print(mutated_population)

Original population
[[1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0.]
 [1. 1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 1. 1. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [1. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 

## Mutation function
See /es1_1_genetic_algorithm/mutation.ipynb to see the above code written as a function that will be used in /es1_1_genetic_algorithm/GA.ipynb.